version: '3.8'

services:
  ngix:
    build: ./nginx
    container_name: ngix-container
    ports:
      - "8080:80"
    depends_on:
      - express
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    networks:
      - app-network

  express:
    build: ./express
    container_name: express-container
    ports:
      - "3000:3000"
    volumes:
      - ./express:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge